### ISSUE TITLE
NPM is NOT a trash

### ISSUE THREAD

**Issue by potato179** [tritiumNetworks/.emmet#1]
![image](https://user-images.githubusercontent.com/44293278/80666885-9d02d900-8ad8-11ea-9f6a-6b52f4319854.png)

NPM이 트래시라니 너무 심한거 아닙니까?

**Comment by comjun04** [comment]
~~저사람 원래 저렇게 말하던데~~

**Comment by noamboy2006** [comment]
agreed. NPM is NOT a trash.

**Comment by pmh-only** [comment]
칫

**Comment by noamboy2006** [comment]
> 칫

공식 사과를 요청합니다

**Comment by pmh-only** [comment]
사과가 뭐지 먹는건감

**Comment by potato179** [comment]
~~그 사과가 apple이 아니라 apologizing 인데..~~

**Comment by potato179** [comment]
아 npm 으로 바꼈네 ㅋㅋㅋㅋ
